# Generated by Django 3.1.6 on 2021-04-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=20, null=True)),
                ('Name1', models.TextField(max_length=20, null=True)),
                ('Address', models.TextField(max_length=20, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
