# Generated by Django 3.1.6 on 2021-04-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='Name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='Name1',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
