# Generated by Django 3.1.6 on 2021-04-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWeb', '0002_auto_20210424_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
