# Generated by Django 3.1.6 on 2021-05-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWeb', '0004_auto_20210516_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='comments',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
