# Generated by Django 3.1.6 on 2021-05-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWeb', '0005_ratings_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='Nums',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='comments',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
