# Generated by Django 3.1.6 on 2021-06-01 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyWeb', '0009_auto_20210528_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ask', models.CharField(max_length=50, null=True)),
                ('Ehours', models.CharField(max_length=50, null=True)),
                ('costumerId', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyWeb.booking')),
            ],
        ),
    ]
