# Generated by Django 3.1.6 on 2021-06-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWeb', '0010_parking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='Choices',
            field=models.CharField(default=False, max_length=50, null=True),
        ),
    ]
