# Generated by Django 3.1.6 on 2021-06-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWeb', '0013_auto_20210612_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='costumerId',
        ),
        migrations.AddField(
            model_name='parking',
            name='costumerId',
            field=models.ManyToManyField(to='MyWeb.Booking'),
        ),
    ]
