# Generated by Django 3.1.6 on 2021-06-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWeb', '0014_auto_20210613_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Num',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='Nums',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='date',
            field=models.DateField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tip',
            name='add',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
