# Generated by Django 3.1.6 on 2021-06-23 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyWeb', '0018_auto_20210623_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetails',
            name='time',
        ),
    ]
